### ISSUE TITLE
ScrollAppBar cannot update with setState

### ISSUE THREAD

**Issue by ChangJoo-Park** [edsonbonfim/scroll_app_bar#4]
https://github.com/ChangJoo-Park/flutter_tab_ui_template/blob/master/lib/main.dart#L117-L132

These lines using state with setState. I expected the UI to change. But It can't

Please see belows.

Using ScrollAppBar

https://i.imgur.com/y0nCyHB.mp4

Using AppBar

https://i.imgur.com/ev64b9O.mp4

**Comment by edsonbonfim** [comment]
Hi @ChangJoo-Park :wave:

Thanks for opening an issue. Hope that this patch fix the bug. If you have some doubts, please let me know!

**Comment by ChangJoo-Park** [comment]
Thanks @edsonbonfim  :+1: 

It works well on 1.0.2 :)  I saw change initState to build. :100:
