### ISSUE TITLE
Support for transparent AppBar

### ISSUE THREAD

**Issue by xJon** [edsonbonfim/scroll_app_bar#6]
Thank you for this useful package!

There's an issue when using a transparent AppBar with this package.
Because in the code the elevation is always set as `elevation: 0.0,` and added later using:
```dart
  Widget _elevation(double heightFactor) {
    return Material(
      elevation: elevation,
      child: _decoratedContainer(heightFactor),
    );
  }
````
Any AppBar with a transparent color will not be rendered as so.

This can be resolved in many ways, such as passing the `Material` widget a `type` property.
It'd be nice to fix this simple incompatibility in the package in any way you find appropriate!

**Comment by mikamyrseth** [comment]
Did you find a way around this?

**Comment by xJon** [comment]
@mikamyrseth Yes. According to the solution I mentioned in my first post, I forked the package to create my own custom `ScrollAppBar` widget, which I passed a `MaterialType` parameter to. Then in the `_elevation(double heightFactor)` function I passed the parameter into the `Material` widget:
```dart
Widget _elevation(double heightFactor) {
    return Material(
      elevation: elevation,
      type: widget.materialType, <---
      child: _decoratedContainer(heightFactor),
    );
  }
```

**Comment by mikamyrseth** [comment]
I'll try this thank you!

**Comment by ncpleslie** [comment]
For those that want to try this, I created a fork.

Add the following to your pubspec.yaml
```
  scroll_app_bar:
    git:
      url: git://github.com/ncpleslie/scroll_app_bar.git
      ref: master
```

Then pass `MaterialType.transparency` through for materialType along with the color `Colors.transparent`.

```
ScrollAppBar(
          controller: scrollController,
          title: Text('My App'),
          centerTitle: true,
          elevation: Theme.of(context).appBarTheme.elevation,
          backgroundColor: Colors.transparent,
          toolbarOpacity: 0.7,
          materialType: MaterialType.transparency,
          actions <Widget>[]);
```

I also created a PR to include this functionality.
